name:                dphs
version:             0.1.0.0
github:              "githubuser/dphs"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/dphs#readme>

dependencies:
- base >= 4.8 && < 5
- compdata >= 0.12 && < 1.0

ghc-options:
- -Wall
- -fwarn-tabs
- -fwarn-incomplete-uni-patterns
- -fwarn-incomplete-record-updates
- -optP-Wno-nonportable-include-path # workaround [Filename case on macOS · Issue #4739 · haskell/cabal](https://github.com/haskell/cabal/issues/4739)

library:
  source-dirs:
    - src
  default-extensions:
    - DataKinds
    - DeriveGeneric
    - DuplicateRecordFields
    - FlexibleContexts
    - TypeApplications
    - DeriveFunctor
    - DeriveFoldable
    - DeriveTraversable
    - TypeOperators
    - ApplicativeDo
    - LambdaCase
    - GeneralizedNewtypeDeriving
    - TypeFamilies
    - ScopedTypeVariables
    - RankNTypes
    - FlexibleInstances
    - DeriveDataTypeable
    - QuasiQuotes
    - TemplateHaskell
    - ConstraintKinds
    - UndecidableInstances
    - MultiParamTypeClasses
    - KindSignatures
    - FunctionalDependencies
    - DataKinds
    - GADTs
    - StandaloneDeriving
    - ViewPatterns
    - CPP
    - PartialTypeSignatures
    - PolyKinds
    - QuantifiedConstraints
    - DerivingVia
    - BangPatterns
    - PatternSynonyms
    - DuplicateRecordFields
    - OverloadedLabels
    - LambdaCase
    - TypeFamilyDependencies
    - OverloadedStrings

executables:
  dphs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dphs

tests:
  dphs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dphs
